### ISSUE TITLE
Preps things for Export Issue

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Shader-Pack#59]
![Unbenannt](https://user-images.githubusercontent.com/49412050/140531646-1e964c78-1d2e-4805-92e9-79e57bfe3881.PNG)

also happens in 2.93.1

**Comment by FlailingFog** [comment]
I was doing the layer selection the wrong way, it should work now

**Comment by LegionInstaller** [comment]
@FlailingFog Sadly No it still doesn't work
![Uploading Unbenannt.PNG…]()

**Comment by LegionInstaller** [comment]
@FlailingFog Hold up I think something went wrong on my side

**Comment by LegionInstaller** [comment]
Yeah it works now
